### ISSUE TITLE
menu select backlight

### ISSUE THREAD

**Issue by kozlyuk** [kozlyuk/smartmed#31]

**Comment by kozlyuk** [comment]
Menu select backlight does not work

**Comment by kozlyuk** [comment]
![image](https://app.gitkraken.com/api/glo/boards/5c7e889a370ef9000fd091b0/attachments/5cd03463630d92000fecdcfe)

**Comment by kozlyuk** [comment]
![image](https://app.gitkraken.com/api/glo/boards/5c7e889a370ef9000fd091b0/attachments/5cd034b2969f01000fc92394)

**Comment by Arrathilar** [comment]
fixed
